"""
Stats API - Provides real-time statistics about Nifty Strategist
"""

import os
import random
import logging
from pathlib import Path
from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from database.session import get_db

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/stats", tags=["stats"])

# Greeting model on OpenRouter — overridable via env.
# inception/mercury-2 is a diffusion model: sub-second latency, English-compliant.
GREETING_MODEL = os.getenv("GREETING_MODEL", "inception/mercury-2")

# English-only fallbacks if the LLM call fails
_FALLBACK_GREETINGS = [
    "Opening bell's live, {name} — grab the tape!",
    "Screens green, {name} — let's hunt some alpha today",
    "{name}, the tape never lies — only traders do",
    "Welcome back, {name} — D-Street's buzzing",
    "{name}, long the dip or short the rip?",
]


def _fallback_greeting(name: str) -> str:
    return random.choice(_FALLBACK_GREETINGS).replace("{name}", name)


@router.get("/tools")
async def get_tools_count():
    """
    Count the number of trading tools available.
    """
    tools_dir = Path(__file__).parent.parent / "tools" / "trading"

    if not tools_dir.exists():
        return {"count": 0, "error": "trading tools directory not found"}

    # Count .py files, excluding __init__.py and test files
    py_files = list(tools_dir.glob("*.py"))
    tool_files = [
        f for f in py_files
        if f.name not in ("__init__.py",) and not f.name.startswith("test_")
    ]

    return {
        "count": len(tool_files),
        "tools": [f.stem for f in tool_files],
        "directory": str(tools_dir)
    }


@router.get("/landing")
async def get_landing_stats(db: AsyncSession = Depends(get_db)):
    """
    Get real-time statistics for the landing page.
    """
    try:
        # Get trading tools count
        tools_dir = Path(__file__).parent.parent / "tools" / "trading"
        py_files = list(tools_dir.glob("*.py")) if tools_dir.exists() else []
        tool_files = [
            f for f in py_files
            if f.name not in ("__init__.py",) and not f.name.startswith("test_")
        ]

        # Count supported stocks from instruments cache
        from services.instruments_cache import symbol_count
        supported_stocks = symbol_count()

        return {
            "toolsCount": len(tool_files),
            "supportedStocks": supported_stocks,
            "paperTrading": True,
            "marketStatus": "Paper Trading Mode"
        }
    except Exception as e:
        # Return safe defaults on error
        return {
            "toolsCount": 5,
            "supportedStocks": 50,
            "paperTrading": True,
            "error": str(e)
        }


@router.get("/greeting")
async def get_homepage_greeting(name: str = Query("trader")):
    """
    Generate a fresh homepage welcome greeting on the fly via DeepSeek V4 Flash.

    English only — a witty one-liner in D-Street trader voice, generated by a
    fast diffusion model. Falls back to a static English greeting if the call fails.
    """
    first_name = (name or "").strip().split()[0] or "trader"

    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        return {"greeting": _fallback_greeting(first_name), "source": "fallback"}

    try:
        import openai

        client = openai.AsyncOpenAI(
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1",
        )

        system = (
            "You write a single short welcome greeting for the homepage of an "
            "Indian stock-market (NSE/BSE) trading assistant. Voice: witty, "
            "punchy Dalal Street trader energy. ENGLISH ONLY — never use Hindi, "
            "Marathi, Gujarati or any other language or transliteration. One "
            "line, under 12 words, no quotes, no emoji, no trailing punctuation "
            "beyond a period or dash. Address the trader by their first name."
        )
        user = f"Write one fresh greeting for a trader named {first_name}."

        resp = await client.chat.completions.create(
            model=GREETING_MODEL,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            temperature=1.1,
            max_tokens=40,
            # If GREETING_MODEL is swapped for a reasoning model, this stops it
            # burning the whole token budget on reasoning (no-op for mercury-2).
            extra_body={"reasoning": {"enabled": False}},
        )
        text = (resp.choices[0].message.content or "").strip().strip('"').strip()
        if not text:
            raise ValueError("empty greeting from model")
        return {"greeting": text, "source": GREETING_MODEL}
    except Exception as e:
        logger.warning(f"Greeting generation failed: {e}")
        return {"greeting": _fallback_greeting(first_name), "source": "fallback"}
