// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/public/notes/:publicId": {
    params: {
      "publicId": string;
    };
  };
  "/auth/upstox/callback": {
    params: {};
  };
  "/chat/:threadId": {
    params: {
      "threadId": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/memory": {
    params: {};
  };
  "/notes": {
    params: {};
  };
  "/notes/:noteId": {
    params: {
      "noteId": string;
    };
  };
  "/tasks": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/mcp": {
    params: {};
  };
  "/automations": {
    params: {};
  };
  "/user": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
  "/admin/docs": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/models": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/help" | "/public/notes/:publicId" | "/auth/upstox/callback" | "/chat/:threadId" | "/dashboard" | "/memory" | "/notes" | "/notes/:noteId" | "/tasks" | "/settings" | "/settings/mcp" | "/automations" | "/user" | "/user/profile" | "/admin/docs" | "/admin/users" | "/admin/models";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "./routes/public.notes.$publicId.tsx": {
    id: "routes/public.notes.$publicId";
    page: "/public/notes/:publicId";
  };
  "./routes/auth.upstox.callback.tsx": {
    id: "routes/auth.upstox.callback";
    page: "/auth/upstox/callback";
  };
  "./routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/chat/:threadId" | "/dashboard" | "/memory" | "/notes" | "/notes/:noteId" | "/tasks" | "/settings" | "/settings/mcp" | "/automations" | "/user" | "/user/profile" | "/admin/docs" | "/admin/users" | "/admin/models";
  };
  "./routes/chat.$threadId.tsx": {
    id: "routes/chat.$threadId";
    page: "/chat/:threadId";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "./routes/memory.tsx": {
    id: "routes/memory";
    page: "/memory";
  };
  "./routes/notes.tsx": {
    id: "routes/notes";
    page: "/notes";
  };
  "./routes/notes.$noteId.tsx": {
    id: "routes/notes.$noteId";
    page: "/notes/:noteId";
  };
  "./routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/tasks";
  };
  "./routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "./routes/settings.mcp.tsx": {
    id: "routes/settings.mcp";
    page: "/settings/mcp";
  };
  "./routes/automations.tsx": {
    id: "routes/automations";
    page: "/automations";
  };
  "./routes/user.tsx": {
    id: "routes/user";
    page: "/user" | "/user/profile";
  };
  "./routes/user.profile.tsx": {
    id: "routes/user.profile";
    page: "/user/profile";
  };
  "./routes/admin.docs.tsx": {
    id: "routes/admin.docs";
    page: "/admin/docs";
  };
  "./routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "./routes/admin.models.tsx": {
    id: "routes/admin.models";
    page: "/admin/models";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/./routes/_index.tsx");
  "routes/login": typeof import("./app/./routes/login.tsx");
  "routes/help": typeof import("./app/./routes/help.tsx");
  "routes/public.notes.$publicId": typeof import("./app/./routes/public.notes.$publicId.tsx");
  "routes/auth.upstox.callback": typeof import("./app/./routes/auth.upstox.callback.tsx");
  "routes/_auth": typeof import("./app/./routes/_auth.tsx");
  "routes/chat.$threadId": typeof import("./app/./routes/chat.$threadId.tsx");
  "routes/dashboard": typeof import("./app/./routes/dashboard.tsx");
  "routes/memory": typeof import("./app/./routes/memory.tsx");
  "routes/notes": typeof import("./app/./routes/notes.tsx");
  "routes/notes.$noteId": typeof import("./app/./routes/notes.$noteId.tsx");
  "routes/tasks": typeof import("./app/./routes/tasks.tsx");
  "routes/settings": typeof import("./app/./routes/settings.tsx");
  "routes/settings.mcp": typeof import("./app/./routes/settings.mcp.tsx");
  "routes/automations": typeof import("./app/./routes/automations.tsx");
  "routes/user": typeof import("./app/./routes/user.tsx");
  "routes/user.profile": typeof import("./app/./routes/user.profile.tsx");
  "routes/admin.docs": typeof import("./app/./routes/admin.docs.tsx");
  "routes/admin.users": typeof import("./app/./routes/admin.users.tsx");
  "routes/admin.models": typeof import("./app/./routes/admin.models.tsx");
};