// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/help": {
    params: {};
  };
  "/public/notes/:publicId": {
    params: {
      "publicId": string;
    };
  };
  "/chat/:threadId": {
    params: {
      "threadId": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/bfcm": {
    params: {};
  };
  "/boxing-week": {
    params: {};
  };
  "/memory": {
    params: {};
  };
  "/notes": {
    params: {};
  };
  "/notes/:noteId": {
    params: {
      "noteId": string;
    };
  };
  "/tasks": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/settings/mcp": {
    params: {};
  };
  "/automations": {
    params: {};
  };
  "/user": {
    params: {};
  };
  "/user/profile": {
    params: {};
  };
  "/price-monitor/*": {
    params: {
      "*": string;
    };
  };
  "/inventory/*": {
    params: {
      "*": string;
    };
  };
  "/cms/*": {
    params: {
      "*": string;
    };
  };
  "/flock/*": {
    params: {
      "*": string;
    };
  };
  "/admin/docs": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/admin/models": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/help" | "/public/notes/:publicId" | "/chat/:threadId" | "/dashboard" | "/bfcm" | "/boxing-week" | "/memory" | "/notes" | "/notes/:noteId" | "/tasks" | "/settings" | "/settings/mcp" | "/automations" | "/user" | "/user/profile" | "/price-monitor/*" | "/inventory/*" | "/cms/*" | "/flock/*" | "/admin/docs" | "/admin/users" | "/admin/models";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "./routes/help.tsx": {
    id: "routes/help";
    page: "/help";
  };
  "./routes/public.notes.$publicId.tsx": {
    id: "routes/public.notes.$publicId";
    page: "/public/notes/:publicId";
  };
  "./routes/_auth.tsx": {
    id: "routes/_auth";
    page: "/chat/:threadId" | "/dashboard" | "/bfcm" | "/boxing-week" | "/memory" | "/notes" | "/notes/:noteId" | "/tasks" | "/settings" | "/settings/mcp" | "/automations" | "/user" | "/user/profile" | "/price-monitor/*" | "/inventory/*" | "/cms/*" | "/flock/*" | "/admin/docs" | "/admin/users" | "/admin/models";
  };
  "./routes/chat.$threadId.tsx": {
    id: "routes/chat.$threadId";
    page: "/chat/:threadId";
  };
  "./routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "./routes/bfcm.tsx": {
    id: "routes/bfcm";
    page: "/bfcm";
  };
  "./routes/boxing-week.tsx": {
    id: "routes/boxing-week";
    page: "/boxing-week";
  };
  "./routes/memory.tsx": {
    id: "routes/memory";
    page: "/memory";
  };
  "./routes/notes.tsx": {
    id: "routes/notes";
    page: "/notes";
  };
  "./routes/notes.$noteId.tsx": {
    id: "routes/notes.$noteId";
    page: "/notes/:noteId";
  };
  "./routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/tasks";
  };
  "./routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "./routes/settings.mcp.tsx": {
    id: "routes/settings.mcp";
    page: "/settings/mcp";
  };
  "./routes/automations.tsx": {
    id: "routes/automations";
    page: "/automations";
  };
  "./routes/user.tsx": {
    id: "routes/user";
    page: "/user" | "/user/profile";
  };
  "./routes/user.profile.tsx": {
    id: "routes/user.profile";
    page: "/user/profile";
  };
  "./routes/price-monitor.tsx": {
    id: "routes/price-monitor";
    page: "/price-monitor/*";
  };
  "./routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory/*";
  };
  "./routes/cms.tsx": {
    id: "routes/cms";
    page: "/cms/*";
  };
  "./routes/flock.tsx": {
    id: "routes/flock";
    page: "/flock/*";
  };
  "./routes/admin.docs.tsx": {
    id: "routes/admin.docs";
    page: "/admin/docs";
  };
  "./routes/admin.users.tsx": {
    id: "routes/admin.users";
    page: "/admin/users";
  };
  "./routes/admin.models.tsx": {
    id: "routes/admin.models";
    page: "/admin/models";
  };
};