"""Models for trade proposals and execution."""

from datetime import datetime
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class TradeProposal(BaseModel):
    """A proposed trade generated by the agent."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str = Field(description="Stock symbol to trade")
    action: Literal["BUY", "SELL"] = Field(description="Trade direction")
    quantity: int = Field(gt=0, description="Number of shares to trade")
    entry_price: float = Field(gt=0, description="Proposed entry price")
    stop_loss: float = Field(gt=0, description="Stop-loss price for risk management")
    target_price: float = Field(gt=0, description="Target price for profit taking")

    # Risk metrics
    risk_reward_ratio: float = Field(
        gt=0, description="Ratio of potential profit to potential loss"
    )
    amount_at_risk: float = Field(
        ge=0, description="Maximum loss in rupees if stop-loss is hit"
    )
    potential_profit: float = Field(
        ge=0, description="Potential profit in rupees if target is reached"
    )

    # Metadata
    analyst_confidence: float = Field(
        ge=0.0, le=1.0, description="Agent's confidence score"
    )
    reasoning: str = Field(
        description="Plain language explanation of the trade thesis"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)


class RiskValidation(BaseModel):
    """Result of risk validation."""

    approved: bool = Field(description="Whether the trade passes risk checks")

    # Position metrics
    position_size_pct: float = Field(
        ge=0, description="This trade as a percentage of portfolio"
    )
    portfolio_exposure_after: float = Field(
        ge=0, description="Total portfolio exposure after this trade"
    )
    daily_loss_impact: float = Field(
        description="Impact on daily P&L if stop-loss is hit"
    )

    # Risk assessment
    risk_score: Literal["low", "medium", "high"] = Field(
        description="Overall risk assessment"
    )
    warnings: list[str] = Field(
        default_factory=list, description="Risk warnings to consider"
    )
    rejection_reason: str | None = Field(
        default=None, description="Reason for rejection if not approved"
    )


class TradeResult(BaseModel):
    """Result of executing a trade via Upstox."""

    success: bool = Field(description="Whether the order was placed successfully")
    order_id: str | None = Field(default=None, description="Upstox order ID")
    status: Literal["PENDING", "COMPLETE", "REJECTED", "CANCELLED"] = Field(
        description="Order status"
    )
    executed_price: float | None = Field(
        default=None, description="Actual execution price"
    )
    executed_quantity: int | None = Field(
        default=None, description="Actual executed quantity"
    )
    message: str = Field(description="Status message or error details")
    timestamp: datetime = Field(default_factory=datetime.utcnow)


class PortfolioPosition(BaseModel):
    """A position in the user's portfolio."""

    symbol: str
    quantity: int
    average_price: float
    current_price: float
    pnl: float
    pnl_percentage: float
    day_change: float
    day_change_percentage: float


class Portfolio(BaseModel):
    """User's portfolio summary."""

    total_value: float = Field(description="Total portfolio value in rupees")
    available_cash: float = Field(description="Available cash for trading")
    invested_value: float = Field(description="Total invested amount")
    day_pnl: float = Field(description="Today's profit/loss")
    day_pnl_percentage: float = Field(description="Today's P&L percentage")
    total_pnl: float = Field(description="Total profit/loss")
    total_pnl_percentage: float = Field(description="Total P&L percentage")
    positions: list[PortfolioPosition] = Field(
        default_factory=list, description="List of current positions"
    )
